version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: brackets/nginx
    ports:
     - "${DOCKER_APP_PORT}:80"
    volumes:
     - .:/var/www/html
    networks:
     - harbornet
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: brackets/php7.1
    environment:
      APP_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
    volumes:
     - .:/var/www/html
     - ./docker/php/ssh:/root/.ssh
     - psyhistory:/root/.config
    networks:
     - harbornet
  pgsql:
    image: postgres:latest
    ports:
     - "${DOCKER_PGSQL_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      PGPASSWORD: "${PGPASSWORD}"
    volumes:
     - pgsqldata:/var/lib/postgresql/data
     - ./docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - ./docker/pgsql/export:/export
     - ./docker/pgsql/import:/import
    networks:
     - harbornet
  testing:
    image: postgres:latest
    ports:
     - "${DOCKER_PGSQL_TEST_PORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      PGPASSWORD: "${PGPASSWORD}"
    volumes:
     - ${DOCKER_PGSQL_TEST_DIR}:/var/lib/postgresql/data
     - ./docker/testing/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
     - harbornet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: brackets/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - harbornet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - harbornet
networks:
  harbornet:
    driver: "bridge"
volumes:
  pgsqldata:
    driver: "local"
  redisdata:
    driver: "local"
  psyhistory:
    driver: "local"
