version: '3.7'
services:
  nginx:
    image: dejwcake/nginx:${HARBOR_NGINX_CONTAINER_VERSION:-1}
    ports:
      - "${HARBOR_WEB_PORT:-80}:80"
    volumes:
      - ./public/:/var/www/html/public:delegated
    networks:
      - harbornet
    depends_on:
      - php
    restart: on-failure

  php:
    image: dejwcake/php${HARBOR_PHP_VERSION:-8.1}:${HARBOR_PHP_CONTAINER_VERSION:-1}
    environment:
      APP_ENV: "${APP_ENV:-local}"
      XDEBUG_HOST: "${HARBOR_XDEBUG_HOST:-host.docker.internal}"
      HARBOR_XDEBUG: "${HARBOR_XDEBUG:-off}"
      HARBOR_USER_UID: "${HARBOR_USER_UID:-1000}"
      TERMINAL_EMULATOR: "${HARBOR_TERMINAL_EMULATOR:-JetBrains-JediTerm}"
    volumes:
      - .:/var/www/html:delegated
      - ${HARBOR_SSH_PATH:-./.harbor/ssh}:/root/.ssh:delegated
      - ${HARBOR_SSH_PATH:-./.harbor/ssh}:/home/harbor/.ssh:delegated
      - ${HARBOR_HISTORY_PATH:-./.harbor/history}/root_bash_history:/root/.bash_history
      - ${HARBOR_HISTORY_PATH:-./.harbor/history}/harbor_bash_history:/home/harbor/.bash_history
      - empty-node-modules:/var/www/html/node_modules
      - composer-cache:/home/harbor/.config/composer/cache
    networks:
      - harbornet
    depends_on:
      - db
      - redis
    restart: on-failure

  db:
    image: dejwcake/postgres${HARBOR_POSTGRES_VERSION:-14}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
    ports:
      - "${HARBOR_DB_PORT:-5432}:${HARBOR_DB_PORT:-5432}"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-laravel}"
      POSTGRES_USER: "${DB_USERNAME:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"
    volumes:
      - db-data:${HARBOR_DB_DATA_PATH:-/var/lib/postgresql/data}
      - ./.harbor/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
      - ./.harbor/db/export:/export:delegated
      - ./.harbor/db/import:/import:cached
    networks:
      - harbornet
    restart: on-failure

  db-testing:
    image: dejwcake/postgres${HARBOR_POSTGRES_VERSION:-14}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
    ports:
      - "${HARBOR_DB_TESTING_PORT:-5433}:${HARBOR_DB_PORT:-5432}"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-laravel}"
      POSTGRES_USER: "${DB_USERNAME:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"
    volumes:
      - ./.harbor/db-testing/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    networks:
      - harbornet
    restart: on-failure

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - harbornet
    restart: on-failure

  node:
    image: dejwcake/node${HARBOR_NODE_VERSION:-16}:${HARBOR_NODE_CONTAINER_VERSION:-1}
    user: node
    volumes:
      - .:/var/www/html:delegated
      - ./public:/var/www/html/public
      - empty-vendor:/var/www/html/vendor
    networks:
      - harbornet

networks:
  harbornet:
    driver: "bridge"

volumes:
  db-data:
    driver: "local"
  redis-data:
    driver: "local"
  empty-node-modules:
    external: true
  empty-vendor:
    external: true
  composer-cache:
    external: true
