version: '3.7'
services:
  nginx:
    image: dejwcake/nginx:${HARBOR_NGINX_CONTAINER_VERSION:-1}
    ports:
     - "${HARBOR_WEB_PORT:-80}:80"
    volumes:
     - ./public/:/var/www/html/public:delegated
    networks:
     - harbornet
  php:
    image: dejwcake/php${HARBOR_PHP_VERSION:-7.4}:${HARBOR_PHP_CONTAINER_VERSION:-1}
    environment:
      APP_ENV: "${APP_ENV:-local}"
      XDEBUG_HOST: "${HARBOR_XDEBUG_HOST:-host.docker.internal}"
      HARBOR_XDEBUG: "${HARBOR_XDEBUG:-off}"
      HARBOR_USER_UID: "${HARBOR_USER_UID:-1000}"
      TERMINAL_EMULATOR: "${HARBOR_TERMINAL_EMULATOR:-JetBrains-JediTerm}"
    volumes:
     - .:/var/www/html:delegated
     - ${HARBOR_SSH_PATH:-./.harbor/php/ssh}:/root/.ssh:delegated
     - ${HARBOR_SSH_PATH:-./.harbor/php/ssh}:/home/harbor/.ssh:delegated
     - psyhistoryroot:/root/.config
     - psyhistoryharbor:/home/harbor/.config
     - nodemodules:/var/www/html/node_modules
     - composercache:/home/harbor/.composer/cache
    networks:
     - harbornet
  postgres:
    image: dejwcake/postgres{HARBOR_POSTGRES_VERSION:-12}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
    ports:
     - "${HARBOR_POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-laravel}"
      POSTGRES_USER: "${DB_USERNAME:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"
    volumes:
     - postgresdata:/var/lib/postgresql/data
     - ./.harbor/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
     - ./.harbor/postgres/export:/export:delegated
     - ./.harbor/postgres/import:/import:cached
    networks:
     - harbornet
  postgrestesting:
    image: dejwcake/postgres{HARBOR_POSTGRES_VERSION:-12}:${HARBOR_POSTGRES_CONTAINER_VERSION:-1}
    ports:
      - "${HARBOR_POSTGRES_TESTING_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE:-laravel}"
      POSTGRES_USER: "${DB_USERNAME:-root}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-bestsecret}"
      PGPASSWORD: "${DB_PASSWORD:-bestsecret}"
    user: postgres
    volumes:
     - postgrestestingdata:/var/lib/postgresql/data:delegated
#     - ${HARBOR_POSTGRES_TESTING_DIR}:/var/lib/postgresql/data:delegated # uncomment to use dir as a filesystem
     - ./.harbor/postgrestesting/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    networks:
     - harbornet
  node:
    image: dejwcake/node{HARBOR_NODE_VERSION:-12}:${HARBOR_NODE_CONTAINER_VERSION:-1}
    user: node
    volumes:
     - .:/var/www/html:delegated
     - ./public:/var/www/html/public
     - vendor:/var/www/html/vendor
    networks:
     - harbornet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - harbornet
networks:
  harbornet:
    driver: "bridge"
volumes:
  postgresdata:
    driver: "local"
  postgrestestingdata:
    driver: "local"
  redisdata:
    driver: "local"
  psyhistoryroot:
    driver: "local"
  psyhistoryharbor:
    driver: "local"
  nodemodules:
    driver: "local"
  vendor:
    driver: "local"
  composercache:
    external: true
